spring:
  profiles:
    active: ${ACTIVE_PROFILE}

---

spring:
  config:
    activate:
      on-profile: prod

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: local
